"""
Bundle downloaded .deb files into a single .tar.gz that installs itself offline.

Layout inside the archive:

    <bundle-name>/
      install.sh      <- chmod +x and run; installs every .deb, no network
      README.txt      <- human instructions
      debs/
        *.deb

The install script finds .debs recursively, so it works no matter how the debs
are arranged under the bundle, and hands the whole set to dpkg at once so dpkg
can resolve install ordering itself.
"""

import io
import os
import tarfile
import time
from typing import List, Optional

from .reporter import Reporter, ConsoleReporter


# The installer is intentionally dependency-free (bash + dpkg + coreutils, all
# present on any Debian/Ubuntu/Raspberry Pi target). {arch} is filled in so the
# script can sanity-check it's being run on the architecture it was built for.
_INSTALL_SH_TEMPLATE = """#!/usr/bin/env bash
#
# Offline installer generated by Debian Package Installer.
# Target architecture: {arch}
#
# Usage:
#   chmod +x install.sh
#   sudo ./install.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

# Re-exec as root if we aren't already (so a plain ./install.sh also works).
if [ "$(id -u)" -ne 0 ]; then
  echo "Root privileges required; re-running with sudo..."
  exec sudo -- bash "$0" "$@"
fi

# Warn (don't hard-fail) if the machine arch differs from what this was built for.
BUILT_FOR="{arch}"
HAVE_ARCH="$(dpkg --print-architecture 2>/dev/null || echo unknown)"
if [ "$BUILT_FOR" != "$HAVE_ARCH" ] && [ "$HAVE_ARCH" != "unknown" ]; then
  echo "WARNING: this bundle was built for '$BUILT_FOR' but this system is '$HAVE_ARCH'." >&2
  echo "         Installation will very likely fail. Continuing in 5 seconds; Ctrl-C to abort." >&2
  sleep 5
fi

# Collect every .deb under the bundle, across any subfolders ("for each folder").
DEBS=()
while IFS= read -r -d '' f; do
  DEBS+=("$f")
done < <(find "$HERE" -type f -name '*.deb' -print0 | sort -z)

if [ "${{#DEBS[@]}}" -eq 0 ]; then
  echo "ERROR: no .deb files found under $HERE" >&2
  exit 1
fi

echo "Found ${{#DEBS[@]}} .deb package(s). Installing offline with dpkg..."

# Give dpkg the whole set at once so it can order them. Pre-Depends cycles can
# need a second pass; --configure -a then finishes anything left half-installed.
dpkg -i "${{DEBS[@]}}" || {{
  echo "First pass reported issues (usually ordering); retrying..."
  dpkg -i "${{DEBS[@]}}" || true
}}
dpkg --configure -a

echo ""
echo "Done. All ${{#DEBS[@]}} package(s) installed."
"""


_README_TEMPLATE = """Offline Debian package bundle
=============================

Built for architecture : {arch}
Packages requested     : {requested}
.deb files included     : {count}

HOW TO INSTALL (on the target machine, no internet needed)
----------------------------------------------------------
  1. Copy this whole folder to the target machine.
  2. chmod +x install.sh
  3. sudo ./install.sh

The installer hands every .deb under this folder to dpkg at once, then runs
`dpkg --configure -a` to finish. No network access is required.

Generated by Debian Package Installer.
"""


def _iter_deb_files(download_dir: str) -> List[str]:
    if not os.path.isdir(download_dir):
        raise FileNotFoundError(f"Download directory not found: {download_dir}")
    debs = sorted(
        os.path.join(download_dir, f)
        for f in os.listdir(download_dir)
        if f.endswith('.deb')
    )
    return debs


def _add_bytes(tar: tarfile.TarFile, arcname: str, data: bytes, mode: int) -> None:
    info = tarfile.TarInfo(name=arcname)
    info.size = len(data)
    info.mode = mode
    info.mtime = int(time.time())
    tar.addfile(info, io.BytesIO(data))


def build_bundle(
    download_dir: str,
    output_path: str,
    target_arch: str,
    package_names: Optional[List[str]] = None,
    reporter: Optional[Reporter] = None,
) -> str:
    """
    Package every .deb in download_dir into a gzip-compressed tar at output_path,
    alongside a generated install.sh (executable) and README.txt. Returns the
    output path. Raises if there are no .deb files to bundle.
    """
    if reporter is None:
        reporter = ConsoleReporter()

    debs = _iter_deb_files(download_dir)
    if not debs:
        raise RuntimeError(
            f"No .deb files found in {download_dir!r}. Download packages before building a bundle."
        )

    # Top-level folder inside the archive = the output filename without .tar.gz,
    # so extracting yields one tidy directory.
    base = os.path.basename(output_path)
    for suffix in (".tar.gz", ".tgz"):
        if base.endswith(suffix):
            base = base[: -len(suffix)]
            break
    top_dir = base or "debian-offline-bundle"

    requested = ", ".join(package_names) if package_names else "(unspecified)"
    install_sh = _INSTALL_SH_TEMPLATE.format(arch=target_arch)
    readme = _README_TEMPLATE.format(
        arch=target_arch, requested=requested, count=len(debs)
    )

    reporter.log(f"Building bundle with {len(debs)} package(s) -> {output_path}")

    out_dir = os.path.dirname(os.path.abspath(output_path))
    os.makedirs(out_dir, exist_ok=True)

    with tarfile.open(output_path, "w:gz") as tar:
        # install.sh with the executable bit set, so even without a manual chmod
        # it's runnable after `tar xzf` on a POSIX target.
        _add_bytes(tar, f"{top_dir}/install.sh", install_sh.encode("utf-8"), mode=0o755)
        _add_bytes(tar, f"{top_dir}/README.txt", readme.encode("utf-8"), mode=0o644)
        for deb in debs:
            tar.add(deb, arcname=f"{top_dir}/debs/{os.path.basename(deb)}")

    reporter.log(f"Bundle written: {output_path}")
    return output_path
